name: SPICE_MARGARITA
channels:
  - https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy>=2.4.2
  - scipy>=1.17.1
  - matplotlib>=3.10.8
  - networkx>=3.6.1
  - nibabel>=5.4.2
  - psutil>=7.2.2
  - tqdm>=4.67.3
  - finufft>=2.4.1
  - scikit-learn>=1.8.0
  - fsl_mrs>=2.4.15
  - fsleyes>=1.19.0
  - pip
  - pip:
    - torch>=2.10.0
    - torchkbnufft==1.4.0
    - mri-nufft>=1.4.0
    - nifti-mrs>=1.4.1
    - fsleyes-plugin-mrs @ git+https://git.fmrib.ox.ac.uk/wclarke/fsleyes-plugin-mrs
